baseURL = ""
title = "Lorenzo Binda"
theme = "hugo-coder-modified"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

#Enable code from markdown:
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Lorenzo Binda"
description = "Lorenzo Binda's personal website"
keywords = "blog,engineer,personal,tech"
info = "Productivity and Tech Enthusiast"
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
footerContent = "Mostly I write whatever comes to my mind."
dateFormat = "2 January 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2021

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 1
url = "https://example.com/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 2
url = "https://example.com/"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 3
url = "https://example.com/"

[[params.social]]
name = "Pocket"
icon = "fa fa-get-pocket"
weight = 4
url = "https://example.com/"

[[params.social]]
name = "GitHub"
icon = "fa fa-github"
weight = 5
url = "https://example.com/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Books"
weight = 2
url = "books/"

[[languages.en.menu.main]]
name = "Contacts"
weight = 3
url = "contact/"

[languages.it]
languageName = ":it:"
title = "Lorenzo Binda"

[languages.it.params]
author = "Lorenzo Binda"
info = "Appassionato di Produttività e Tecnologia"
description = "Sito personale di Lorenzo Binda"
keywords = "blog,ingegnere,persoonale,tecnologia"
footerContent = "Qui scrivo quello che mi passa per la testa."

[[languages.it.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.it.menu.main]]
name = "Libri"
weight = 2
url = "books/"

[[languages.it.menu.main]]
name = "Contatti"
weight = 3
url = "contact/"
